name: quizzly
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # for design
  lottie: ^2.4.0
  # for url
  url_launcher: ^6.1.11
  # for media
  audioplayers: ^4.1.0
  # for localizations
  flutter_localizations:
     sdk: flutter
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


   uses-material-design: true
   generate: true

   assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/

   fonts:
     - family: DMSans
       fonts:
         - asset: assets/fonts/DMSans-Bold.ttf
           weight: 700
         - asset: assets/fonts/DMSans-Medium.ttf
           weight: 500
         - asset: assets/fonts/DMSans-Regular.ttf
           weight: 400
     - family: ExpletusSans
       fonts:
         - asset: assets/fonts/ExpletusSans-Regular.ttf
           weight: 400
